### ISSUE TITLE
FaissSearcher

### ISSUE THREAD

**Issue by malinphy** [texttron/hyde#1]
```
searcher = FaissSearcher('contriever_msmarco_index/', query_encoder)
```
running this command automatically crashes the notebook (I have 24 GB of ram). Basically, it exceeds the RAM and gives errors. Is there any lightweight version of the project? 

Thanks in advance.

**Comment by MXueguang** [comment]
Hi, currently we don't have a smaller prebuilt index, the index itself is around 25GB, so a machine with 32GB RAM should be enough to run it. If that still not works for you, let me know, I can create a product quantized index, which should have much smaller size, (but may have some performance drop)

**Comment by malinphy** [comment]
Thanks for your quick response. I was planning to run the demo but with other libraries, the RAM exceeds 30 GB. A quantized index version would be excellent if it will not take too much time for you. Thanks in advance. 
Best regards.

**Comment by MXueguang** [comment]
Hi, sorry for late reply,
https://www.dropbox.com/s/9nulx9nxn4chujw/faiss.msmarco-v1-passage.contriever.pq-m192.tar.gz
This is a compressed one with PQ. size is about 2GB.
Just replace this path with the original one should work.

**Comment by malinphy** [comment]
Thanks for your effort and kindness. I will try the new file. Thanks again. 

Best Regards.

**Comment by MXueguang** [comment]
:> I'll close the issue for now, feel free to re open if there is further issue
