### ISSUE TITLE
Unable to reproduce the result of Contriever fine-tuned on MS-MARCO

### ISSUE THREAD

**Issue by BeastyZ** [texttron/hyde#6]
Hi, I am reproducing the results of your paper. Base on your provided code, I try to reproduce the ndcg@10(DL19) result of Contriever fine-tuned on MS-MARCO. But I get the 46.85 of ndcg@10 on the DL19 dataset, not 62.1 in the paper. Could you offer the relevant code? Thanks.

**Comment by MXueguang** [comment]
I just replaced corpus index and query encoder model with the fine tuned one in the Jupyter notebook. Could you provide more details on what did you try?

**Comment by BeastyZ** [comment]
I'm sorry. I made a mistake. I didn't replace the corpus index. 
By the way, could you offer more information about building corpus index? Please include the source of the original corpus and the specific fields used to build the index. I would appreciate it very much if you would do so.

**Comment by MXueguang** [comment]
Hi, I used tevatron to create the index. https://github.com/texttron/tevatron/blob/main/examples/example_msmarco.md exactly same script here. I.e. Text field and also the prepended title are used to encode. One thing to note here is tevatron by default use cls token as representation, so for now we need to manually modify corresponding code to change it to avg pooling, and the output need to manually convert to the format in pyserini. I should have pre encoded corpus stored somewhere, I'll see if I can find it and send you Dropbox link. But I am afk now, have to do that tonight.

**Comment by MXueguang** [comment]
https://www.dropbox.com/scl/fi/lqu5ofd5xyiwj6takwv6z/contriever_ft_msmarco_index.tar?rlkey=ys31elo4mnm1sbqhva6wc9y76&dl=0

See if this link works?

**Comment by BeastyZ** [comment]
Thank you for your timely and useful help! We successfully constructed the index of contriever-ft based on the original [MSMARCO collection](https://msmarco.z22.web.core.windows.net/msmarcoranking/collection.tar.gz) by following the official [readme](https://github.com/castorini/pyserini/blob/master/docs/usage-index.md#building-a-dense-vector-index) and got the 67.5 of ndcg@10 on the DL19, better than the result in your paper.

**Comment by MXueguang** [comment]
cool， just to clarify, 62.1 in our paper is original fine tuned contriever. Ft contriever with Hyde is in table 4.
